'''
NOTE
this code takes in data generated by main.py and compiles it into groups of four data points.
for example, 6 frames will give you 3 groups - [0:4], [1:5], [2:6]
a while later i decided to use 5
'''

infile = open('jump_dataset.csv', 'r')
outfile = open('slide_dataset.csv', 'w')
proper = standing = sitting = ''
line = infile.readline()
while line:
    stuff = line.split(',')
    name = stuff[-1][:-1]
    if name == 'proper':
        proper += ','.join(stuff[:-1]) + '\n'
    elif name == 'standing':
        standing += ','.join(stuff[:-1]) + '\n'
    elif name == 'sitting':
        sitting += ','.join(stuff[:-1]) + '\n'
    else:
        print(f"{name} is unknown")
        break
    line = infile.readline()

def slide(thing, name):
    arr = thing.split('\n')
    ans = []
    for i in range(len(arr) - 5):
        ans.append(','.join(arr[i:i+5]) + f',{name}')
    return ans

for i in slide(proper, 'proper'):
    outfile.write(i + '\n')

for i in slide(standing, 'standing'):
    outfile.write(i + '\n')

for i in slide(sitting, 'sitting'):
    outfile.write(i + '\n')
